# Generated by Django 3.2.5 on 2021-07-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=32)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField()),
            ],
        ),
    ]
