# Generated by Django 3.2.5 on 2021-07-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='sourсe',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='currency_name',
        ),
    ]
