# Generated by Django 3.2.5 on 2021-08-09 09:11

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 9, 9, 11, 56, 128989, tzinfo=utc)), # noqa
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=2047),
        ),
    ]
