# Generated by Django 3.2.5 on 2021-08-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_responcelog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponceLog',
            new_name='ResponseLog',
        ),
    ]
