# Generated by Django 3.2.5 on 2021-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_rename_responcelog_responselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='response_time',
            field=models.PositiveSmallIntegerField(help_text='in milliseconds'),
        ),
    ]
