# Generated by Django 3.2.5 on 2021-08-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_alter_responselog_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='responselog',
            name='request_method',
            field=models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], default='GET', max_length=8),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_name',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
    ]
