# Generated by Django 3.2.5 on 2021-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20210826_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='request_method',
            field=models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], max_length=8),
        ),
    ]
