# Generated by Django 3.2.5 on 2021-08-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_alter_responselog_request_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='bank_name',
            new_name='source',
        ),
    ]
